create table `cytus2-level`
(
    id                bigint auto_increment
        primary key,
    name              varchar(200)                              not null,
    actor_id          char(20)                                  null,
    difficulty_hard   int                                       not null comment 'HARD 难度定数等级 * 100',
    difficulty_chaos  int                                       not null comment 'CHAOS 难度定数等级 * 100',
    difficulty_glitch int                                       null comment 'GLITCH 难度等级 * 100; 为空则无绿谱',
    deleted           tinyint(1)                   default 0    not null comment '是否被新版删除',
    free              tinyint(1)                   default 0    not null comment '是否可以免费获得(除绿谱)',
    nicks             longtext collate utf8mb4_bin default '[]' not null,
    constraint `cytus2-level_cytus2-actor_id_fk`
        foreign key (actor_id) references `cytus2-actor` (id),
    constraint nicks
        check (json_valid(`nicks`))
)
    comment 'Cytus2 歌曲库';

INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('100sec Cat Dreams', 'NEKO#ΦωΦ', 700, 1475, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('99 Glooms', 'Ivy', 700, 1375, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('彩', 'Rin', 900, 1525, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('超常マイマイン', 'Graff.J', 800, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('都市の呼吸', 'Alice', 700, 1275, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('粉骨砕身カジノゥ', 'Graff.J', 1000, 1400, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('風の声', 'Aroma', 400, 925, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('眷戀', 'Crystal PuNK', 500, 1100, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('決戦', 'Rin', 700, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('黎明-REIMEI-', 'Bobo', 600, 1125, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('魔法みたいなミュージック！', 'Miku', 700, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('漂流', 'Aroma', 700, 1400, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('気楽なCloudy', 'NEKO#ΦωΦ', 800, 1275, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('三灯火', 'Rin', 800, 1250, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('神样と羊饲い', 'Bobo', 800, 1250, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('時計の部屋と精神世界', 'Graff.J', 900, 1400, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('下水鳴動して鼠一匹', 'NEKO#ΦωΦ', 700, 1325, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('響け!', 'NEKO#ΦωΦ', 800, 1275, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('小悪魔×3の大脫走！？', 'NEKO#ΦωΦ', 900, 1400, null, 1, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('「妖怪録、我し来にけり。 」', 'Rin', 800, 1425, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('一啖兩啖', 'Neko', 700, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('月西江', 'Miku', 500, 800, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Abduction', 'ConneR', 800, 1100, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Absolutely', 'JOE', 500, 1150, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Accelerator', 'Nora', 700, 1375, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Accelerator', 'ROBO_Head', 700, 1400, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('AIAIAI (feat. 中田ヤスタカ)', 'Kizuna AI', 800, 1150, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Alexandrite', 'Ivy', 700, 1400, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Alterna Pt.1 -Cosmogony-', 'NEKO#ΦωΦ', 500, 1150, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Amenemhat', 'Sagar', 800, 1350, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Anchor', 'Vanessa', 500, 950, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('ANiMA', 'Alice', 1000, 1500, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Anzen Na Kusuri', 'Aroma', 600, 1050, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Aphasia', 'ConneR', 700, 1275, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('A Portent of the Silver Wheel', 'Sagar', 700, 1325, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Aragami', 'Hans', 900, 1400, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Area184', 'Ivy', 800, 1175, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Armaros', 'ROBO_Head', 800, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Ascension to Heaven', 'Graff.J', 800, 1500, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Ask to Wind Live Mix', 'Graff.J', 800, 1025, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('AssaultMare', 'Ivy', 900, 1425, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Asylum', 'Xenon', 700, 1225, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('ATONEMENT', 'Nora', 600, 1100, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Äventyr', 'Bobo', 700, 1250, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Awakening', 'ROBO_Head', 500, 1050, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Baptism of Fire (CliqTrack remix)', 'PAFF', 700, 1175, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Bass Music', 'JOE', 800, 1325, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Bastard of Hardcore', 'Nora', 700, 1325, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Beautiful Lie', 'Aroma', 600, 1100, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Better than your error system', 'NEKO#ΦωΦ', 800, 1400, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Biotonic', 'Ivy', 700, 1300, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Blackest Luxury Car', 'Graff.J', 700, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Black Hole', 'Xenon', 400, 975, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Blah!!', 'Neko', 800, 1400, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('BloodyMare', 'Ivy', 800, 1300, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Bloody Purity', 'Ivy', 800, 1425, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Blossoms for Life', 'PAFF', 700, 1175, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Blow my mind', 'NEKO#ΦωΦ', 900, 1400, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Blow My Mind (tpz Overheat Remix)', 'NEKO#ΦωΦ', 700, 1425, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Blue Star', 'Miku', 600, 1000, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('BlythE', 'Graff.J', 800, 1225, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Body Talk', 'PAFF', 800, 1150, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Brain Power', 'NEKO#ΦωΦ', 800, 1225, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Brave My Heart', 'Graff.J', 700, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('BREAK IT', 'Miku', 800, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Break The Core', 'ROBO_Head', 900, 1350, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Break Through The Barrier', 'ROBO_Head', 800, 1350, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Bring the light', 'Aroma', 500, 900, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Bullet Waiting for Me (James Landino remix)', 'PAFF', 400, 1150, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Caliburne ～Story of the Legendary sword～', 'Graff.J', 900, 1525, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Can''t Make a Song!!', 'Miku', 700, 1125, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Capture me', 'Cherry', 700, 1125, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Capybara Kids'' Paradise', 'NEKO#ΦωΦ', 900, 1475, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Celestial Sounds (KIVΛ Remix)', 'ROBO_Head', 800, 1500, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Centimeter Johnny', 'Graff.J', 800, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Chandelier XIII', 'Crystal PuNK', 600, 1275, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('change', 'Aroma', 500, 950, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Chaos and Abyss -3rd Movement-', 'Vanessa', 1000, 1450, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('CHAOS', 'ROBO_Head', 900, 1475, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('CHAOS //System Offline//', 'Vanessa', 800, 1250, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Childish', 'JOE', 700, 1200, null, 1, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Chocolate Missile', 'Neko', 600, 1325, 1400, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Chosen', 'Xenon', 700, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Chrome VOX', 'NEKO#ΦωΦ', 900, 1450, 1550, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Circus Time', 'Graff.J', 700, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Cityscape', 'PAFF', 600, 1175, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Claim the Game', 'ROBO_Head', 700, 1175, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('CODE NAME: GAMMA', 'NEKO#ΦωΦ', 900, 1475, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('CODE NAME: SIGMA', 'Ivy', 900, 1475, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('cold', 'ROBO_Head', 700, 1175, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('concentric circles', 'Xenon', 700, 1225, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('conflict', 'Ivy', 900, 1525, 1550, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Conundrum', 'Graff.J', 700, 1200, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('CREDENCE', 'Cherry', 800, 1125, 1300, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Crimson Fate', 'Crystal PuNK', 800, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Cristalisia', 'Ivy', 600, 1250, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Cybernetic', 'Miku', 700, 1350, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Dance till Dawn', 'Nora', 600, 1075, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Dark Madness', 'Crystal PuNK', 700, 1350, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Darling Staring...', 'Crystal PuNK', 700, 1375, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Dasein', 'ROBO_Head', 700, 1325, 1400, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Deadly Slot Game', 'ROBO_Head', 700, 1350, 1400, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Dead Master', 'ROBO_Head', 900, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Dead Point', 'ROBO_Head', 800, 1325, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Dead V-Code (Special Edit)', 'Graff.J', 800, 1400, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Decade', 'Miku', 600, 875, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Deep Dive', 'Crystal PuNK', 600, 1350, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Demetrius', 'ConneR', 600, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Deus Ex Machina', 'ConneR', 800, 1250, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Devilic Sphere', 'ROBO_Head', 900, 1300, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('DigiGroove', 'Ivy', 700, 1250, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('dimensionalize nervous breakdown (rev.flat)', 'ROBO_Head', 700, 1375, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('DJ Mashiro is dead or alive', 'Neko', 900, 1425, null, 1, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Doldrums', 'Sagar', 700, 1400, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('DON’T STOP ROCKIN’', 'Graff.J', 800, 1250, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Dream', 'Hans', 600, 1100, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('D R G', 'Ivy', 600, 1150, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Dropping Lightspeed', 'NEKO#ΦωΦ', 900, 1500, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Drop The World', 'Nora', 800, 1450, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Duality', 'Vanessa', 800, 1100, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('dynamo', 'Graff.J', 800, 1400, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Effervesce', 'Crystal PuNK', 600, 1325, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Elysium', 'Sagar', 600, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('EMber', 'ROBO_Head', 700, 1225, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('End of fireworks', 'Bobo', 600, 1025, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('End of the Moonlight', 'Graff.J', 700, 1250, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Ephemeral', 'Hans', 700, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Eternity', 'Nora', 700, 1125, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('extinguisher', 'NEKO#ΦωΦ', 700, 1100, 1425, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Fade Into The Darkness', 'ROBO_Head', 900, 1350, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Fading Star', 'Graff.J', 700, 1100, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Familiar Craze', 'Crystal PuNK', 800, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Favorites', 'PAFF', 500, 1050, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Fight Another Day (Andy Tunstall remix)', 'PAFF', 600, 1000, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Fighting', 'Xenon', 700, 1150, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Final Step!', 'Graff.J', 700, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Fireflies (Funk Fiction remix)', 'PAFF', 600, 875, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Firstborns', 'Bobo', 800, 1400, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Floor of Lava', 'ConneR', 1000, 1575, null, 1, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('For You the Bellz Toll', 'NEKO#ΦωΦ', 700, 1275, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('FREEDOM DiVE↓', 'Ivy', 1000, 1575, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Friction', 'Alice', 700, 1150, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('FUJIN Rumble', 'Graff.J', 900, 1225, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Fur War, Pur War', 'ConneR', 800, 1525, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('FUSE', 'Graff.J', 800, 1400, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('future base (Prod. Yunomi)', 'Kizuna AI', 600, 1125, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Gekkouka', 'ConneR', 800, 1150, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Gigantic Saga', 'Graff.J', 600, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Glass Wall', 'Miku', 600, 1025, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Glorious Crown', 'Graff.J', 1000, 1625, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('glory day', 'Graff.J', 800, 1175, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Grand Emotion', 'Nora', 600, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Gravity', 'PAFF', 700, 1300, 1350, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Green Hope', 'PAFF', 700, 1150, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Grimoire of Crimson', 'ROBO_Head', 800, 1100, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Hagiasmos', 'ROBO_Head', 700, 1275, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Halcyon', 'Ivy', 900, 1350, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Halloween Party', 'Ivy', 900, 1525, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Happiness Breeze', 'NEKO#ΦωΦ', 700, 1125, 1425, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Hard Landing', 'NEKO#ΦωΦ', 800, 1100, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Heat Ring', 'Ivy', 700, 1150, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Heliopolis Project', 'Bobo', 700, 1200, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('hello, alone (Prod. MATZ)', 'Kizuna AI', 600, 1000, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Hello Days', 'Graff.J', 700, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Hello, Morning (Prod. Nor)', 'Kizuna AI', 700, 1225, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Hello Pinky', 'Graff.J', 700, 1150, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Hesitant Blade', 'Graff.J', 500, 1100, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Higher and Higher', 'JOE', 600, 1350, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Homebound Train & Moving Thoughts', 'Ivy', 500, 900, null, 1, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Hop Step Adventure☆', 'Graff.J', 700, 1400, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('hunted', 'Cherry', 600, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Hydra', 'NEKO#ΦωΦ', 800, 1200, 1625, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Hydrangea', 'JOE', 600, 1250, 1425, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('IBUKI', 'Bobo', 700, 1200, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('I can avoid it.#φωφ', 'Neko', 700, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('I hate to tell you', 'Alice', 800, 1225, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('͟͝͞Ⅱ́̕', 'Vanessa', 900, 1500, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('II-V', 'Vanessa', 700, 1200, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('iL', 'Ivy', 1000, 1600, null, 1, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('I luv U', 'ConneR', 700, 1000, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Immram Brain', 'Sagar', 600, 1350, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('I''M NOT', 'Cherry', 600, 1075, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Imprinting', 'ConneR', 800, 1250, 1500, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Inari', 'Rin', 600, 950, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('INSPION', 'Xenon', 900, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Inspiration', 'PAFF', 500, 950, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Instinct', 'ConneR', 800, 1150, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Interstellar Experience', 'Graff.J', 800, 1400, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('IOLITE-SUNSTONE', 'Xenon', 700, 1075, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('I Wish You Were Mine', 'PAFF', 700, 1175, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Jakarta PROGRESSION', 'Nora', 800, 1450, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Jazzy Glitch Machine', 'ROBO_Head', 800, 1375, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Juicy Gossip', 'JOE', 700, 1175, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('KANATA', 'PAFF', 600, 900, 1175, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Karma', 'Xenon', 700, 1125, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Keep it up', 'NEKO#ΦωΦ', 800, 1325, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Leaving All Behind', 'Ivy', 700, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Legacy', 'Alice', 500, 900, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Legacy', 'Sagar', 700, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('LEVEL4', 'Cherry', 700, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Leviathan', 'Hans', 900, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Libera Me', 'Ivy', 800, 1350, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Liberation', 'NEKO#ΦωΦ', 900, 1400, 1575, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Lifill', 'Graff.J', 700, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Light of Buenos Aires', 'ConneR', 700, 1175, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Lights of Muse', 'Graff.J', 800, 1400, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Light up my love!!', 'PAFF', 800, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Lilac for Anabel', 'PAFF', 700, 1225, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Living for you (Andy Tunstall remix)', 'Cherry', 700, 1125, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Living In The One', 'Alice', 700, 1025, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Log In', 'Neko', 600, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Lost in the Nowhere', 'Hans', 800, 1400, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('LOUDER MACHINE', 'NEKO#ΦωΦ', 800, 1225, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('L''Ultima Cena', 'ConneR', 800, 1325, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Lunar Mare', 'Ivy', 800, 1450, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Luolimasi', 'ROBO_Head', 700, 1100, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Maboroshi', 'NEKO#ΦωΦ', 900, 1375, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Magical Toy Box', 'Graff.J', 900, 1500, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Make Me Alive', 'PAFF', 500, 925, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Make Me Burn', 'ROBO_Head', 600, 1350, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Make U Mine', 'Aroma', 600, 1125, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Malstream', 'Crystal PuNK', 600, 1225, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Mammal', 'Neko', 900, 1400, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Marigold', 'Alice', 900, 1550, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Mari-Temari', 'Rin', 600, 1250, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Masquerade', 'Ivy', 700, 1150, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Medusa', 'Graff.J', 800, 1400, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('meet you (Prod. DÉ DÉ MOUSE)', 'Kizuna AI', 500, 1225, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('melty world (Prod. TeddyLoid)', 'Kizuna AI', 800, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Midnight', 'ROBO_Head', 700, 1400, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Miku', 'Miku', 600, 1000, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Milky Way Galaxy (SIHanatsuka Remix)', 'ROBO_Head', 800, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('miracle step (Prod. Nor)', 'Kizuna AI', 500, 1125, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('mirai (Prod. ✰Taku Takahashi)', 'Kizuna AI', 600, 950, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('More Than Diamond', 'PAFF', 500, 925, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Nautilus', 'JOE', 500, 1125, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Neon Escape', 'Aroma', 600, 1000, null, 1, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('New Challenger Approaching', 'Ivy', 800, 1475, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('New World', 'PAFF', 600, 1025, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('new world (Prod. Yunomi)', 'Kizuna AI', 700, 1100, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Nídhögg', 'Sagar', 900, 1375, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Nightmare', 'Graff.J', 1000, 1550, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Nocturnal Type', 'ROBO_Head', 800, 1125, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('No-Effected World', 'PAFF', 600, 900, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('No One Can''t Stop Me', 'Aroma', 500, 1100, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('NORDLYS', 'Bobo', 800, 1225, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Nostalgia Sonatina', 'ConneR', 800, 1200, null, 1, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('NRG_Tech', 'ROBO_Head', 700, 1325, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Obey', 'Graff.J', 700, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('OBLIVION', 'Graff.J', 700, 1100, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Occidens', 'Ivy', 700, 1450, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Olympia', 'ConneR', 600, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('One Way Love', 'NEKO#ΦωΦ', 600, 900, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Online', 'NEKO#ΦωΦ', 800, 1325, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Open the Game', 'JOE', 600, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Oshama Scramble!', 'Graff.J', 800, 1400, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('over the reality (Prod. Avec Avec)', 'Kizuna AI', 700, 1225, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('paradigm-paragramme-program', 'Ivy', 900, 1375, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Path and Period', 'Hans', 800, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Perspectives', 'Aroma', 500, 1050, 1300, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Phagy Mutation', 'Nora', 700, 1300, null, 1, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Phantom Razor', 'Xenon', 800, 1275, 1425, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Pink Graduation', 'Neko', 700, 1025, null, 1, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('PIXIE DUST', 'PAFF', 500, 1050, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Platinum', 'Hans', 500, 900, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Play The Future', 'Graff.J', 500, 1275, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('popotnik - The Traveller of Ljubljana', 'Graff.J', 700, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Pounding Destination', 'Graff.J', 400, 1025, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Praystation (HiTECH NINJA Remix)', 'NEKO#ΦωΦ', 800, 1375, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Pressure', 'Ivy', 700, 1275, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Pure Powerstomper', 'ROBO_Head', 800, 1250, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Purge', 'Ivy', 800, 1225, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Qualia', 'Ivy', 900, 1325, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Quantum Labyrinth', 'Ivy', 700, 1225, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Quinsialyn', 'Bobo', 700, 1375, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Ramen is God', 'NEKO#ΦωΦ', 900, 1450, 1625, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Ra', 'Vanessa', 800, 1225, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Realize', 'Cherry', 800, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('REBELLIUM', 'ConneR', 900, 1450, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Rebirth', 'NEKO#ΦωΦ', 700, 1175, 1550, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Re:Boost', 'PAFF', 500, 1125, 1300, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Recall', 'PAFF', 600, 900, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Red Five', 'Ivy', 700, 1375, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Re:incRnaTiØN ～夕焼ケ世界ノ決別ヲ～', 'Neko', 900, 1600, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Rei', 'NEKO#ΦωΦ', 700, 1225, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('REmorse', 'NEKO#ΦωΦ', 900, 1450, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Reset', 'Ivy', 700, 1225, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Restriction', 'ROBO_Head', 700, 1050, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Resurrection', 'NEKO#ΦωΦ', 800, 1200, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('RETRIEVE', 'Cherry', 700, 1125, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Return of the Lamp', 'Sagar', 800, 1350, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Return', 'Xenon', 600, 1100, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Re:VeLΔTiØN ～光道ト破坏ノ双白翼～', 'NEKO#ΦωΦ', 900, 1425, 1600, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('R.I.P.', 'Neko', 900, 1450, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Rosa Rubus', 'Vanessa', 600, 1100, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Ruins in the Mirage', 'Hans', 600, 1000, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Run Go Run', 'Hans', 700, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Sacrifice', 'Sagar', 700, 1375, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Saika', 'Ivy', 700, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Sairai', 'Xenon', 500, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Samurai', 'Xenon', 900, 1400, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Scenery in your eyes', 'Cherry', 600, 1000, null, 1, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Sdorica The Story Unfolds', 'Graff.J', 500, 1100, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Secret Garden', 'Ivy', 600, 1025, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('SECRET;WEAPON', 'PAFF', 800, 1375, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Sentimental Journey', 'Ivy', 700, 1400, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Sharing The World', 'Miku', 600, 925, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('SHIRO', 'ROBO_Head', 600, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Sickest City', 'ROBO_Head', 700, 1525, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Silent Voice', 'Graff.J', 600, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Sleeping Beast', 'PAFF', 700, 900, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Snow Blossom', 'Bobo', 800, 1250, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('So In Love', 'PAFF', 600, 1125, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Sovereign', 'Ivy', 800, 1300, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Space Alien', 'Sagar', 800, 1375, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Spotlight On', 'Aroma', 600, 1175, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Spring', 'Graff.J', 800, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Standby for Action', 'JOE', 800, 1225, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Stargazer', 'Graff.J', 600, 1000, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Starlight (KIVΛ Remix)', 'Nora', 600, 1100, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Starry Summoner', 'Rin', 500, 1075, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Stewrica -Cross-', 'Graff.J', 800, 1250, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Still', 'Cherry', 600, 1100, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Still（Piano Version）', 'Crystal PuNK', 500, 900, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Stop at nothing (Andy Tunstall remix)', 'Cherry', 700, 1100, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Stranger', 'NEKO#ΦωΦ', 600, 1175, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Summer Zephyr', 'Ivy', 600, 1025, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Sunday Night Blues', 'NEKO#ΦωΦ', 500, 975, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Sunset', 'Hans', 600, 1100, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Sunshine Duration', 'Crystal PuNK', 700, 1225, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Super attractor', 'PAFF', 900, 1375, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Survive', 'PAFF', 500, 1025, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('sweet conflict', 'Graff.J', 700, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Symmetry', 'Ivy', 900, 1500, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('SYSTEMFEIT', 'Cherry', 700, 1275, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('syūten', 'Vanessa', 500, 1050, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Take me to the Future', 'JOE', 700, 1375, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Ten Thousand Stars', 'Miku', 600, 1250, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('The 89''s Momentum', 'Graff.J', 700, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('The 90''s Decision', 'Graff.J', 800, 1400, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('The Beautiful Moonlight', 'Alice', 700, 950, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('The breath of the soul', 'Bobo', 700, 1400, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('The Cross (Feat. Silvia Su)', 'Crystal PuNK', 600, 1175, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('The Grand Debate', 'Rin', 700, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('The Siege', 'Rin', 800, 1225, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('The Spark', 'NEKO#ΦωΦ', 800, 1200, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('The Whole Rest', 'Vanessa', 700, 1225, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Time to Fight', 'Ivy', 900, 1400, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('To Further Dream', 'Ivy', 700, 1250, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Tokiwatari', 'Ivy', 700, 1300, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('TOKONOMA Spacewalk', 'NEKO#ΦωΦ', 700, 1275, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('tondari-hanetari', 'ConneR', 800, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('to next page', 'Alice', 800, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('To the Light', 'Xenon', 800, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Tunnef''s Nightmare', 'ROBO_Head', 900, 1400, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Turnstile Jumper', 'JOE', 700, 1350, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('U.A.D', 'Graff.J', 700, 1250, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Ultimate feat. 放課後のあいつ', 'Xenon', 800, 950, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Under the same sky', 'PAFF', 700, 875, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('UnNOT!CED', 'NEKO#ΦωΦ', 700, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Until the Blue Moon Rises', 'Graff.J', 600, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Uranus', 'Nora', 800, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Used to be', 'Vanessa', 500, 975, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Utopiosphere', 'Alice', 700, 1025, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('velkinta feat. Cikado & A-Tse', 'Crystal PuNK', 600, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Venus di Ujung Jari', 'Miku', 500, 700, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Violet', 'Xenon', 700, 1500, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('ViRUS', 'ROBO_Head', 800, 1175, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('VIS::CRACKED', 'Ivy', 900, 1575, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('V.', 'Ivy', 1000, 1550, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('V.R.W (feat. shully)', 'Crystal PuNK', 600, 1150, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('V. //System Offline//', 'Vanessa', 800, 1300, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Walnuts Walkers', 'NEKO#ΦωΦ', 800, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('We''re All Gonna Die', 'Graff.J', 1000, 1550, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('What''s Your PR.Ice?', 'Ivy', 700, 1175, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Whisper in my Head', 'Xenon', 700, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Who Am I?', 'PAFF', 600, 1025, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Wicked Ceremony', 'Ivy', 800, 1400, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Winter Games', 'PAFF', 500, 975, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('XING', 'Graff.J', 800, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Xiorc', 'ConneR', 1000, 1350, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('XODUS', 'Graff.J', 1000, 1500, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('XYZ', 'Vanessa', 900, 1525, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('YUBIKIRI-GENMAN', 'Alice', 600, 900, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Zealous Hearts (Rayark Edit)', 'NEKO#ΦωΦ', 700, 1100, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('βinαrΨ', 'Crystal PuNK', 700, 1225, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('すゝめ☆クノイチの巻', 'Rin', 900, 1425, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('そんなに私を期待させないで', 'Graff.J', 700, 1100, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('ラッキー☆オーブ (3R2 Remix)', 'Miku', 700, 1075, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('ラッキー☆オーブ', 'Miku', 700, 1075, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('リラ', 'Neko', 800, 1225, null, 0, 0, '[]');
