create table `cytus2-level`
(
    id                bigint auto_increment
        primary key,
    name              varchar(200)                              not null,
    actor_id          char(20)                                  null,
    difficulty_hard   int                                       not null comment 'HARD 难度定数等级 * 100',
    difficulty_chaos  int                                       not null comment 'CHAOS 难度定数等级 * 100',
    difficulty_glitch int                                       null comment 'GLITCH 难度等级 * 100; 为空则无绿谱',
    deleted           tinyint(1)                   default 0    not null comment '是否被新版删除',
    free              tinyint(1)                   default 0    not null comment '是否可以免费获得(除绿谱)',
    nicks             longtext collate utf8mb4_bin default '[]' not null,
    constraint `cytus2-level_cytus2-actor_id_fk`
        foreign key (actor_id) references `cytus2-actor` (id),
    constraint nicks
        check (json_valid(`nicks`))
)
    comment 'Cytus2 歌曲库';

INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('100sec Cat Dreams', 'NEKO#ΦωΦ', 800, 1475, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('99 Glooms', 'Ivy', 700, 1375, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('A Portent of the Silver Wheel', 'Sagar', 700, 1325, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('AIAIAI', 'Kizuna AI', 800, 1150, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('ATONEMENT', 'Nora', 600, 1100, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Abduction', 'ConneR', 800, 1100, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Absolutely', 'JOE', 500, 1150, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Accelerator', 'Nora', 700, 1375, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Accelerator', 'ROBO_Head', 700, 1400, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Alexandrite', 'Ivy', 700, 1400, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Alterna Pt.1 -Cosmogony-', 'NEKO#ΦωΦ', 500, 1150, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Amenemhat', 'Sagar', 800, 1350, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Anchor', 'Vanessa', 500, 950, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Anzen Na Kusuri', 'Aroma', 600, 1050, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Aphasia', 'ConneR', 700, 1275, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Area184', 'Ivy', 800, 1175, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Armaros', 'ROBO_Head', 800, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Ask to Wind Live Mix', 'NEKO#ΦωΦ', 800, 1025, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('AssaultMare', 'Ivy', 900, 1425, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Asylum', 'Xenon', 700, 1225, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Awakening', 'ROBO_Head', 500, 1050, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('BREAK IT', 'Miku', 800, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Baptism of Fire', 'PAFF', 700, 1175, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Bass Music', 'JOE', 800, 1325, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Bastard of Hardcore', 'Nora', 700, 1325, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Beautiful Lie', 'Aroma', 600, 1100, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Biotonic', 'Ivy', 700, 1300, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Black Hole', 'Xenon', 400, 975, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Blah!!', 'Neko', 900, 1400, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Bloody Purity', 'Ivy', 800, 1425, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('BloodyMare', 'Ivy', 800, 1300, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Blossoms for Life', 'PAFF', 600, 1175, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Blow My Mind (tpz Overheat Remix)', 'NEKO#ΦωΦ', 900, 1450, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Blow my mind', 'NEKO#ΦωΦ', 900, 1400, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Blue Star', 'Miku', 600, 1000, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('BlythE', 'NEKO#ΦωΦ', 800, 1225, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Body Talk', 'PAFF', 100, 1150, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Brain Power', 'NEKO#ΦωΦ', 800, 1225, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Break The Core', 'ROBO_Head', 900, 1350, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Break Through The Barrier', 'ROBO_Head', 800, 1350, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Bring the light', 'Aroma', 500, 900, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Bullet Waiting for Me', 'PAFF', 400, 1150, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('CHAOS //System Offline//', 'Vanessa', 800, 1250, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('CHAOS', 'ROBO_Head', 900, 1475, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('CODE NAME: GAMMA', 'NEKO#ΦωΦ', 900, 1475, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('CODENAME : SIGMA', 'Ivy', 900, 1475, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('CREDENCE', 'Cherry', 800, 1125, 1300, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Caliburne ~Story of the Legendary sword~', 'NEKO#ΦωΦ', 900, 1525, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Can''t Make a Song!!', 'Miku', 700, 1125, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Capture me', 'Cherry', 700, 1125, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Capybara Kids'' Paradise', 'NEKO#ΦωΦ', 800, 1475, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Celestial Sounds', 'ROBO_Head', 800, 1500, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Chandelier XIII', 'Crystal PuNK', 600, 1275, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Chaos and Abyss -3rd Movement-', 'Vanessa', 1000, 1450, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Chocolate Missile', 'Neko', 600, 1325, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Chosen', 'Xenon', 700, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Chrome VOX', 'NEKO#ΦωΦ', 900, 1450, 1550, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Cityscape', 'PAFF', 500, 1175, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Claim the Game', 'ROBO_Head', 700, 1175, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Crimson Fate', 'Crystal PuNK', 800, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Cristalisia', 'Ivy', 600, 1250, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Cybernetic', 'Miku', 700, 1350, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('D R G', 'Ivy', 600, 1150, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('DON''T STOP ROCKIN''', 'NEKO#ΦωΦ', 800, 1250, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Dance till Dawn', 'Nora', 600, 1075, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Dark Madness', 'Crystal PuNK', 700, 1325, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Darling Staring...', 'Crystal PuNK', 700, 1375, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Dasein', 'ROBO_Head', 700, 1325, 1400, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Dead Master', 'ROBO_Head', 900, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Dead Point', 'ROBO_Head', 800, 1325, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Deadly Slot Game', 'ROBO_Head', 700, 1350, 1400, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Decade', 'Miku', 600, 875, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Deep Dive', 'Crystal PuNK', 600, 1350, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Demetrius', 'ConneR', 600, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Deus Ex Machina', 'ConneR', 800, 1250, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Devilic Sphere', 'ROBO_Head', 900, 1300, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('DigiGroove', 'Ivy', 700, 1275, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Doldrums', 'Sagar', 700, 1400, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Drop The World', 'Nora', 800, 1450, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Duality', 'Vanessa', 800, 1100, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('EMber', 'ROBO_Head', 700, 1225, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Effervesce', 'Crystal PuNK', 600, 1325, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Elysium', 'Sagar', 600, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('End of the Moonlight', 'NEKO#ΦωΦ', 700, 1250, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Eternity', 'Nora', 700, 1125, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('FREEDOM DiVE', 'Ivy', 1000, 1575, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('FUJIN Rumble', 'NEKO#ΦωΦ', 700, 1500, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Fade Into The Darkness', 'ROBO_Head', 900, 1350, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Familiar Craze', 'Crystal PuNK', 800, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Favourites', 'PAFF', 500, 1050, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Fight Another Day', 'PAFF', 600, 1000, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Fighting', 'Xenon', 700, 1150, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Fireflies', 'PAFF', 600, 875, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('For You the Bellz Toll', 'NEKO#ΦωΦ', 900, 1425, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Fur War, Pur War', 'ConneR', 800, 1525, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Gekkouka', 'ConneR', 800, 1150, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Glass Wall', 'Miku', 600, 1025, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Glorious Crown', 'NEKO#ΦωΦ', 1000, 1625, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Grand Emotion', 'Nora', 600, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Gravity', 'PAFF', 700, 1300, 1350, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Green Hope', 'PAFF', 700, 1125, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Grimoire of Crimson', 'ROBO_Head', 800, 1100, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Hagiasmos', 'ROBO_Head', 800, 1275, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Halloween Party', 'Ivy', 900, 1525, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Happiness Breeze', 'NEKO#ΦωΦ', 700, 1125, 1425, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Hard Landing', 'NEKO#ΦωΦ', 800, 1100, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Heat Ring', 'Ivy', 700, 1150, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Hello Pinky', 'NEKO#ΦωΦ', 700, 1150, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Hello, Morning', 'Kizuna AI', 700, 1225, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Hesitant Blade', 'NEKO#ΦωΦ', 500, 1200, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Higher and Higher', 'JOE', 600, 1350, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Hydra', 'NEKO#ΦωΦ', 900, 1200, 1625, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Hydrangea', 'JOE', 600, 1250, 1425, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('I Wish You Were Mine', 'PAFF', 700, 1175, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('I can avoid it.', 'Neko#φωφ', 700, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('I luv U', 'ConneR', 700, 1000, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('I''M NOT', 'Cherry', 600, 1075, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('II-V', 'Vanessa', 700, 1200, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('II', 'Vanessa', 900, 1500, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('INSPION', 'Xenon', 900, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('IOLITE-SUNSTONE', 'Xenon', 700, 1075, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Immram Brain', 'Sagar', 600, 1325, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Imprinting', 'ConneR', 800, 1250, 1500, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Inari', 'Rin', 600, 975, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Instinct', 'ConneR', 800, 1150, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Jakarta PROGRESSION', 'Nora', 800, 1450, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Jazzy Glitch Machine', 'ROBO_Head', 800, 1375, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Juicy Gossip', 'JOE', 700, 1175, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('KANATA', 'PAFF', 600, 900, 1175, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Karma', 'Xenon', 700, 1125, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Keep it up', 'NEKO#ΦωΦ', 800, 1325, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('L''Ultima Cena', 'ConneR', 800, 1325, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('LEVEL4', 'Cherry', 700, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Leaving All Behind', 'Ivy', 700, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Legacy', 'Sagar', 700, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Libera Me', 'Ivy', 800, 1350, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Liberation', 'NEKO#ΦωΦ', 900, 1400, 1575, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Light of Buenos Aires', 'ConneR', 700, 1175, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Light up my love!!', 'PAFF', 900, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Lilac for Anabel', 'PAFF', 800, 1225, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Living for you', 'Cherry', 700, 1125, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Log In', 'Neko', 800, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Lunar Mare', 'Ivy', 800, 1450, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Luolimasi', 'ROBO_Head', 700, 1100, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Maboroshi', 'NEKO#ΦωΦ', 700, 1375, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Make Me Alive', 'PAFF', 800, 925, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Make Me Burn', 'ROBO_Head', 600, 1350, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Make U Mine', 'Aroma', 600, 1125, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Malstream', 'Crystal PuNK', 600, 1225, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Mammal', 'Neko', 700, 1400, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Mari-Temari', 'Rin', 600, 1250, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Masquerade', 'Ivy', 700, 1150, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Midnight', 'ROBO_Head', 700, 1400, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Miku', 'Miku', 600, 1000, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Milky Way Galaxy', 'ROBO_Head', 800, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('More Than Diamond', 'PAFF', 600, 925, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('NRG_Tech', 'ROBO_Head', 700, 1325, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Nautilus', 'JOE', 500, 1125, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('New Challenger Approaching', 'Ivy', 800, 1475, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('New World', 'PAFF', 500, 1025, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Nightmare', 'NEKO#ΦωΦ', 1000, 1550, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('No One Can''t Stop Me', 'Aroma', 500, 1100, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Nocturnal Type', 'ROBO_Head', 800, 1125, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Nídhögg', 'Sagar', 900, 1375, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('OBLIVION', 'NEKO#ΦωΦ', 700, 1100, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Occidens', 'Ivy', 700, 1450, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Olympia', 'ConneR', 600, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('One Way Love', 'NEKO#ΦωΦ', 600, 900, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Online', 'NEKO#ΦωΦ', 700, 1325, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Open the Game', 'JOE', 600, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Oshama Scramble!', 'NEKO#ΦωΦ', 800, 1400, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('PIXIE DUST', 'PAFF', 500, 1050, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Perspectives', 'Aroma', 500, 1050, 1300, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Phantom Razor', 'Xenon', 800, 1275, 1425, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Play The Future', 'NEKO#ΦωΦ', 500, 1275, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Praystation', 'NEKO#ΦωΦ', 700, 1375, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Pressure', 'Ivy', 700, 1225, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Pure Powerstomper', 'ROBO_Head', 800, 1250, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Purge', 'Ivy', 800, 1225, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Qualia', 'Ivy', 900, 1325, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Quantum Labyrinth', 'Ivy', 700, 1225, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('R.I.P.', 'Neko', 900, 1450, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('REBELLIUM', 'ConneR', 900, 1450, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('RETRIEVE', 'Cherry', 700, 1125, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('REmorse', 'NEKO#ΦωΦ', 500, 1450, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Ra', 'Vanessa', 800, 1225, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Ramen is God', 'NEKO#ΦωΦ', 900, 1450, 1625, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Re:Boost', 'PAFF', 500, 1125, 1300, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Re:VeLΔTiØN ～光道ト破壞ノ雙白翼～', 'NEKO#ΦωΦ', 700, 1425, 1600, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Re:incRnaTiØN ～夕焼ケ世界ノ決別ヲ～', 'Neko', 600, 1600, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Realize', 'Cherry', 800, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Rebirth', 'NEKO#ΦωΦ', 700, 1175, 1550, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Recall', 'PAFF', 500, 900, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Red Five', 'Ivy', 700, 1375, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Rei', 'NEKO#ΦωΦ', 600, 1225, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Reset', 'Ivy', 700, 1225, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Restriction', 'ROBO_Head', 700, 1050, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Resurrection', 'NEKO#ΦωΦ', 800, 1200, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Return of the Lamp', 'Sagar', 800, 1350, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Return', 'Xenon', 600, 1100, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Rosa Rubus', 'Vanessa', 600, 1100, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('SECRET;WEAPON', 'PAFF', 600, 1375, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('SHIRO', 'ROBO_Head', 600, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('SYSTEMFEIT', 'Cherry', 700, 1275, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Sacrifice', 'Sagar', 700, 1375, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Saika', 'Ivy', 700, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Sairai', 'Xenon', 500, 950, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Samurai', 'Xenon', 900, 1400, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Sdorica The Story Unfolds', 'NEKO#ΦωΦ', 500, 1025, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Sentimental Journey', 'Ivy', 700, 1400, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Sharing The World', 'Miku', 600, 925, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Sickest City', 'ROBO_Head', 700, 1525, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Sleeping Beast', 'PAFF', 700, 900, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('So In Love', 'PAFF', 700, 1125, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Sovereign', 'Ivy', 800, 1300, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Space Alien', 'Sagar', 800, 1375, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Spotlight On', 'Aroma', 600, 1175, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Standby for Action', 'JOE', 800, 1225, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Starlight', 'Nora', 600, 1100, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Starry Summoner', 'Rin', 500, 1075, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Still', 'Cherry', 600, 1100, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Stop at nothing', 'Cherry', 700, 1100, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Stranger', 'NEKO#ΦωΦ', 900, 1175, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Summer Zephyr', 'Ivy', 600, 1025, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Sunday Night Blues', 'NEKO#ΦωΦ', 700, 975, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Sunshine Duration', 'Crystal PuNK', 700, 1225, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Super Attractor', 'PAFF', 600, 1375, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Survive', 'PAFF', 500, 1025, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Symmetry', 'Ivy', 900, 1500, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('TOKONOMA Spacewalk', 'NEKO#ΦωΦ', 700, 1275, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Take me to the Future', 'JOE', 700, 1375, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Ten Thousand Stars', 'Miku', 600, 1250, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('The Cross', 'Crystal PuNK', 600, 1175, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('The Grand Debate', 'Rin', 700, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('The Siege', 'Rin', 800, 1225, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('The Spark', 'NEKO#ΦωΦ', 800, 1200, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('The Whole Rest', 'Vanessa', 700, 1225, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Time to Fight', 'Ivy', 900, 1400, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('To Further Dream', 'Ivy', 700, 1250, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('To the Light', 'Xenon', 800, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Tokiwatari', 'Ivy', 700, 1300, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Tunnef''s Nightmare', 'ROBO_Head', 900, 1400, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Turnstile Jumper', 'JOE', 700, 1350, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('U.A.D', 'NEKO#ΦωΦ', 700, 1250, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Ultimate', 'Xenon', 800, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('UnNOT!CED', 'NEKO#ΦωΦ', 700, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Under the same sky', 'PAFF', 700, 875, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Uranus', 'Nora', 800, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Used to be', 'Vanessa', 500, 975, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('V. //System Offline//', 'Vanessa', 800, 1300, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('V.R.W', 'Crystal PuNK', 600, 1150, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('V.', 'Ivy', 1000, 1550, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('VIS::CRACKED', 'Ivy', 900, 1575, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Venus di Ujung Jari', 'Miku', 500, 700, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('ViRUS', 'ROBO_Head', 800, 1175, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Violet', 'Xenon', 700, 1500, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Walnuts Walkers', 'NEKO#ΦωΦ', 800, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('We''re All Gonna Die', 'NEKO#ΦωΦ', 1000, 1550, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('What''s Your PR.Ice?', 'Ivy', 700, 1175, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Whisper in my Head', 'Xenon', 700, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Who Am I?', 'PAFF', 700, 1025, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Wicked Ceremony', 'Ivy', 800, 1400, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Winter Games', 'PAFF', 600, 975, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('XYZ', 'Vanessa', 900, 1525, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Xiorc', 'ConneR', 1000, 1350, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('Zealous Hearts', 'NEKO#ΦωΦ', 700, 1100, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('change', 'Aroma', 500, 950, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('cold', 'ROBO_Head', 700, 1175, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('concentric circles', 'Xenon', 700, 1225, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('conflict', 'Ivy', 900, 1525, 1550, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('dimensionalize nervous breakdown', 'ROBO_Head', 700, 1375, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('extinguisher', 'NEKO#ΦωΦ', 800, 1100, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('future base', 'Kizuna AI', 600, 1125, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('glory day', 'NEKO#ΦωΦ', 800, 1175, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('hello, alone', 'Kizuna AI', 600, 1000, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('hunted', 'Cherry', 600, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('meet you', 'Kizuna AI', 500, 1225, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('melty world', 'Kizuna AI', 800, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('miracle step', 'Kizuna AI', 500, 1125, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('mirai', 'Kizuna AI', 600, 950, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('new world', 'Kizuna AI', 700, 1100, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('over the reality', 'Kizuna AI', 700, 1225, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('syuten', 'Vanessa', 500, 1050, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('tondari-hanetari', 'ConneR', 800, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('velkinta', 'Crystal PuNK', 600, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('βinαrΨ', 'Crystal PuNK', 700, 1225, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('「妖怪録、我し来にけり。 」', 'Rin', 800, 1425, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('すゝめ☆クノイチの巻', 'Rin', 900, 1450, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('ラッキー☆オーブ (3R2 Remix)', 'Miku', 700, 1075, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('ラッキー☆オーブ', 'Miku', 700, 1075, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('リラ', 'Neko', 800, 1225, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('一啖兩啖', 'Neko', 700, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('三燈火', 'Rin', 800, 1250, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('下水鳴動して鼠一匹', 'NEKO#ΦωΦ', 900, 1325, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('彩', 'Rin', 900, 1525, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('月西江', 'Miku', 500, 800, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('気楽なCloudy', 'NEKO#ΦωΦ', 800, 1275, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('決戦', 'Rin', 700, 1200, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('漂流', 'Aroma', 700, 1400, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('超常マイマイン', 'NEKO#ΦωΦ', 800, 1300, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('響け!', 'NEKO#ΦωΦ', 800, 1275, null, 0, 1, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('風の声', 'Aroma', 400, 925, null, 0, 0, '[]');
INSERT INTO `cytus2-level` (name, actor_id, difficulty_hard, difficulty_chaos, difficulty_glitch, deleted, free, nicks) VALUES ('魔法みたいなミュージック！', 'Miku', 700, 1300, null, 0, 0, '[]');
